Finally, CI/CD code updated

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,7 @@
-name: CI and CD
+# Work flow name
+name: React Native CI/CD Workflow
 
+# While push and pull request to main branch - that is when the workflow will be triggered
 on:
   push:
     branches:
@@ -8,25 +10,31 @@ on:
     branches:
       - main
 
+# First Job: Lint and Test
 jobs:
   lint-and-test:
+    # Ubuntu-latest is virtual machine which provided by GitHub. Job are running on this machine.
     runs-on: ubuntu-latest
 
     steps:
+      # Repo code pull into this machine
       - name: Checkout code
         uses: actions/checkout@v2
 
+      # Install JDK17 install, Needs android & fastlane build.
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
           java-version: '17'
           distribution: 'temurin'
 
+      # Install Node.js 22.9.0, for needed for build and install node modules
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '22.9.0'
 
+      # Cache node modules, so that it won't be installed every time
       - name: Cache Node.js modules
         uses: actions/cache@v3
         with:
@@ -35,18 +43,23 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-node-
 
+      # Install Node.js dependencies, according to (Package.json) file.
       - name: Install Node.js dependencies
         run: npm install
 
+      # Code formatting using with prettier syntax
       - name: Run Prettier
         run: npm run format
 
+      # Code linting using with eslint syntax
       - name: Run ESLint
         run: npm run lint:fix
 
+      # Run unit tests using with jest syntax
       #   - name: Run Unit Tests
       #     run: npm run test
 
+      # Run Detox tests using with detox syntax
       # - name: Run Detox tests
       #   uses: reactivecircus/android-emulator-runner@v2
       #   with:
@@ -66,6 +79,7 @@ jobs:
       # Prefer to run localy e2e beacause it requires high computation and cost much on cloud services
       # If you have money go with Genymotion 0.05$ per minute😁
 
+      # If any steps failed, it will stop the workflow and send a notification to Discord
       - name: Send Discord notification on failure
         if: failure()
         run: |
@@ -74,6 +88,7 @@ jobs:
                -d '{"content": "🚨 CI/CD Build Failed! Error logs: Testing / Linting / Prettier Failed!"}' \
                ${{ secrets.DISCORD_WEBHOOK_URL }}
 
+      # If all steps passed, it will send a success notification to Discord
       - name: Send Discord notification on success
         if: success()
         run: |
@@ -82,6 +97,7 @@ jobs:
                -d '{"content": "✅ Testing Passed"}' \
                ${{ secrets.DISCORD_WEBHOOK_URL }}
 
+  # Second Job: Deploy - This job is deployed job, needs to be run after the first job
   deploy:
     runs-on: ubuntu-latest
     needs: lint-and-test
@@ -112,15 +128,24 @@ jobs:
       - name: Install Node.js dependencies
         run: npm install
 
+      # For the play-store, required keystore file must be added to the GitHub secrets
       - name: Restore Keystore File
         run: |
-          echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}" | base64 --decode > android/app/my-upload-key.keystore
+          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/app/my-upload-key.keystore
+
+      - name: Debug CI Context
+        run: |
+          pwd
+          cat android/fastlane/playstore-credentials.json || echo "❌ Credentials file not found"
+          ls android/app/ | grep keystore || echo "❌ Keystore not found"
+          ls -R android
 
       - name: Install Fastlane
         run: sudo gem install fastlane -NV
 
       - name: Deploy to Google Play Store
         run: |
+          echo "${{ secrets.PLAYSTORE_CREDENTIALS }}" | base64 --decode > android/fastlane/playstore-credentials.json
           cd android
           fastlane playstore
 
